### ISSUE TITLE
LSP support

### ISSUE THREAD

**Issue by sje30** [gcv/julia-snail#1]
Hi,
this looks like a great project, thanks for sharing.  Have you seen the other work by @tpapp:

https://github.com/tpapp/julia-repl

Would the LSP emacs support help with your project at all (e.g. to provide a debugger?)

Am happy to help test.  (I am an ESS core developer, although with not as much time as before to work on developing code.  I think our ESS julia support is okay, but it is good to see other approaches like this test out ideas.)

PS I think adopting vterm for the inferior process is interesting.

**Comment by tpapp** [comment]
FWIW, the endgame for julia-repl (which is a quick hack) is to be replaced by something like 

1. this package, or
2. @RobBlackwell's https://github.com/RobBlackwell/Swank.jl,
3. something else based on LSP.

At the moment 1. or 2. look the most promising to me --- modeling after CIDER and SLIME should be lightweight and viable, LSP is somewhat heavy.

**Comment by sje30** [comment]
Had not seen the Swank.jl interface work by @RobBlackwell before, thanks for that.  

LSP does indeed seem heavy, but if it can help save some Emacs recoding (having spent years with ESS trying to interface with R), I'd like to see how LSP can be made a bit leaner.  It seems efforts are progressing in this area: http://blog.binchen.org/posts/how-to-speed-up-lsp-mode.html

**Comment by gcv** [comment]
Thanks for your comments.

I also have not seen Swank.jl. For what it's worth, I started working on Snail in the fall of 2019, and the first public release of Swank.jl was at the very end of December of 2019. There's likely some duplicated effort at this point, though I spent most of my time on the parser, not the protocol. In any case, plugging into Swank+SLIME has historically not worked out for non-Common Lisp languages. Clojure started out with a Swank back-end, but ended up moving to nrepl+CIDER. Since this happened in 2009-2010, I no longer remember the technical reasons. I also vaguely recall that Scheme backends had problems.

As for LSP, I tried it several times, most recently about 6 months ago. Did not like eglot or lsp-mode with Ruby or Python, though it was acceptable with TypeScript using tide. LSP servers and clients seem to fundamentally expect to run a dedicated server process separate from the image executing the program being developed. This increases environment and configuration complexity, and is a poor fit for languages with a strong REPL-based development model. I'm sure some of these problems can be worked around, but I have no interest in doing this, especially since it would mean writing yet another LSP client in Emacs (4th, if you count eglot, lsp-mode, and tide). Plugging into lsp-mode is an option, but I have looked at it and have no interest in that project.
