### ISSUE TITLE
vterm-shell is changed globally after running julia-snail

### ISSUE THREAD

**Issue by orialb** [gcv/julia-snail#10]
When calling `julia-snail` it changes `vterm-shell` variable to:
`julia -L PATH/TO/JULIA-SNAIL/JuliaSnail.jl`
This change seems to be global, which means that if I try to just open a new `vterm` buffer for some other uses it will open Julia instead of an actual shell.

**Comment by gcv** [comment]
Could you please double-check that this happens in a fresh Emacs session, and there's nothing potentially changing `vterm-shell` somewhere else? The dynamic variable is only rebound in a `let` form, so that binding should disappear as soon as the `let` form terminates. I don't see any sign of `vterm-shell` being stuck in either REPL or source buffers.

**Comment by orialb** [comment]
You are right, I probably messed up this variable when trying to debug one of the other issues. 
It works fine with a fresh session.
