### ISSUE TITLE
using `symbol-file` can be brittle

### ISSUE THREAD

**Issue by MasonProtter** [gcv/julia-snail#147]
Julia Snail currently uses `symbol-file` to locate itself, but that seems to cause trouble. E.g.: https://github.com/radian-software/straight.el/issues/1150#issuecomment-1971611667

**Comment by gcv** [comment]
Can you try replacing calls to `(symbol-file 'julia-snail)` with `(find-library-name "julia-snail")` and check if that works better?

**Comment by MasonProtter** [comment]
That seems to also not work.

**Comment by raxod502** [comment]
Why not use `load-file-name`?

**Comment by gcv** [comment]
@raxod502: Because `load-file-name` is always `nil` in development when I'm changing functions and reloading Elisp source buffers. It feels like it might break in other situations.

Based on the documentation quoted in the Straight ticket, I see why `symbol-file` doesn't work, but I'm far more confused about why `find-library-name` fails.

Also, with the Straight changes happening, does Snail have to be modified at all to resolve this?

**Comment by raxod502** [comment]
I typically use `(or load-file-name buffer-file-name)` when initializing a variable for the location of my library. It seems to handle all cases both in development and production.

I haven't looked into `find-library-name` at all so I can't comment on that at the moment.

As far as continuing to use `symbol-file`... I guess if it works, it works, but I would be worried about it failing in the future because (as documented in the Emacs manual), it is not guaranteed to return an actual filepath, and may just return the library name instead.

**Comment by gcv** [comment]
`(or load-file-name buffer-file-name)` doesn't work (1) when it's used in a function that has been redefined, and (2) called when the current buffer is not the one where it was redefined. It probably works most of the time, but I feel like I'll mess up when using it.

@MasonProtter: It looks like I've also used `locate-library` for this purpose. Not sure why `symbol-file` ended up the shipping implementation. I have no clue why `find-library-name` didn't work for you, or what the difference between `locate-library` and `find-library-name` might be. For now, I pushed a change replacing `symbol-file` with `locate-library`. It seems to work for me. Please try it and let me know.

**Comment by raxod502** [comment]
> (or load-file-name buffer-file-name) doesn't work (1) when it's used in a function that has been redefined, and (2) called when the current buffer is not the one where it was redefined

Right, that's why I define a variable with the value, and then use that variable anywhere I need. It's more performant than scanning `load-path` at runtime, anyway.

But it is fine either way you prefer to write the code.

**Comment by gcv** [comment]
Please reopen if this is still something I should look into.
