### ISSUE TITLE
Much longer precompilation on Using (~570secs) with Snail than without (8secs)

### ISSUE THREAD

**Issue by jdm204** [gcv/julia-snail#159]
Hi, **many thanks** for Snail, I use it near daily!

I've noticed that precompile times are bad for me recently in projects with several dependencies (I don't know how recently) and output a lot of warnings. As part of debugging that I opened a fresh bash session in eat and started Julia without Snail, and I was surprised to see precompilation take less than 8 seconds given I had gotten used to 500+ seconds.

**Is this at all expected**, that M-x `julia-snail`, activating the Project, and running this line:

```
@time using Distributions, Turing, DifferentialEquations, CairoMakie, DataFrames, CSV, StaticArrays
```

**should take many times longer than starting Julia normally** through a shell? The output also contains many more warnings.
I've attached the output from both scenarios.

[repro_snail.txt](https://github.com/user-attachments/files/16349641/repro_snail.txt)
[repro_nosnail.txt](https://github.com/user-attachments/files/16349643/repro_nosnail.txt)

emacs: 31.0.50
Snail: 1.3.2
Julia: 1.10.4
OS: Ubuntu 24.04

Snail config:

```
(use-package julia-snail
   :custom
   (julia-snail-terminal-type :eat)
   (julia-snail-executable "~/.juliaup/bin/julia")
   (julia-snail-extra-args "--threads=4")
   (julia-snail-extensions '(ob-julia)))
```

Also the Project.toml for the project: 
[Project.toml.txt](https://github.com/user-attachments/files/16349672/Project.toml.txt)

**Comment by gcv** [comment]
Thank you for the detailed report, but I cannot reproduce this at all. Also using Julia 1.10.4, though on a Mac and with Emacs 29.4. My (very old) machine takes 17-18 seconds to load those packages (after the initial installation step) whether or not Snail is loaded.

Is your environment local-only? Are you using any remote Snail features? Is your home and working directory located on a local disk, or on a network or a cluster filesystem?

What happens if you load Snail without Emacs? You can try `julia --project=/path/to/project -L /path/to/emacs/package/installation/area/julia-snail-1.3.2/JuliaSnail.jl`, then run `JuliaSnail.start(10011)` (or whatever port). Then try your timing command.

I wonder if your `~/.julia` directory is corrupted or misbehaving. Would you be willing to delete `artifacts`, `compiled`, and `packages` from it and try again? You’ll have to reinstall all your packages, unfortunately.

**Comment by jdm204** [comment]
Many thanks for the reply!

> Is your environment local-only? Are you using any remote Snail features? Is your home and working directory located on a local disk, or on a network or a cluster filesystem?

It's all local on a laptop (I will have to look into these remote features for future HPC work).

> What happens if you load Snail without Emacs?

Good idea. Wow:

```
julia --project=/home/jdm204/growthcurves/ -L /home/jdm204/.config/emacs/elpaca/repos/julia-snail/JuliaSnail.jl -ie 'JuliaSnail.start(10011); @time using Distributions, Turing, DifferentialEquations, CairoMakie, DataFrames, CSV, StaticArrays'
```

```
8.297053 seconds (12.46 M allocations: 961.175 MiB, 13.21% gc time, 4.78% compilation time: 30% of which was recompilation)
```

I then tried the normal way through emacs again, and, 350 seconds. I found this spooky so I nuked `.julia`, reinstalled from juliaup, reinstalled packages, tried again...

...and now it's 8 seconds however I run the code. It seems to be working now so feel free to just close and move on, but if you have any idea how a borked `.julia` could cause this issue only with snail+emacs I would certainly be curious!

Thanks again, long live snail!

**Comment by gcv** [comment]
Not sure. Do you install Emacs from Flatpak by any chance? That (sometimes?) runs apps in containers, and I can maybe see that causing cross-filesystem problems.
