### ISSUE TITLE
Eat Buffer *julia* process has no process

### ISSUE THREAD

**Issue by jlapeyre** [gcv/julia-snail#165]
I get the error  `Buffer *julia* process has no process` when running either
`julia-snail-send-buffer-file` or `julia-snail-send-buffer-line`

There is a buffer named `*julia*` and a functional julia process is running in it.

The same error occurs if I use `vterm` instead of  `eat`.

* emacs 29.4
* eat 0.9.4
* julia-snail 20240812.840
* vterm 20240705.1533

**Comment by gcv** [comment]
Could you post the exact steps you took to get a Snail REPL? Also anything interesting from the `*Messages*` buffer. Also the contents of the Julia REPL after startup.

**Comment by jlapeyre** [comment]
Just tried it again and it *is* working. I'm not sure why. I was pretty careful experimenting yesterday. Restarting emacs many times, trying small changes.

I neglected to include the Julia version in my original message above. It was Julia v1.11.0. However, in the meantime, I upgraded to v1.11.1. (I'm not using juliaup. I suppose I could try if this made a difference.)

I am 99% sure that yesterday `M-x julia-snail` opened a buffer with a Julia repl, and I saw nothing but the Julia prompt. Today, this is inserted into the buffer: ` JuliaSnail.start(10011)`. And the two commands mentioned above work. I can't think of anything else I changed. I did not modify my init.el since yesterday.

If I start emacs and immediately do `M-x julia-snail`, I see a julia REPL, but not  `JuliaSnail.start(10011)`. The minibuffer shows "Wrong type argument: stringp, ni". I have to open a buffer with Juila code first. Then `M-x julia-snail` seems to work correctly. Note this is *not* the problem I had when I opened this issue. There was no error in the minibuffer.

**Comment by gcv** [comment]
- The problem you had is consistent with the Snail server not starting on the Julia side, i.e. `JuliaSnail.start` not getting called. It’s not obvious why this happened, or why it stopped happening. The culprit is probably the code that pastes the string `JuliaSnail.start(…)` into the REPL buffer. It’s the only way to interact with the REPL before the Snail server opens a network socket, and if it fails, I’m not sure what happens. I don’t think I’ve run into that before.
- Calling `julia-snail` without a Julia file does indeed cause the `Wrong type argument` error. I should put in a check for that.
- `julia-repl-mode` isn’t really compatible with Snail. It may introduce subtle conflicts (mainly with keybindings).

**Comment by jlapeyre** [comment]
It looks like everything is either known, or I am unable to reproduce it.
I'll close this issue.
