### ISSUE TITLE
High level workflow question: Revise + julia-snail

### ISSUE THREAD

**Issue by christopher-dG** [gcv/julia-snail#25]
Thanks for this package! It's really useful so far.

I'm trying to adapt my current workflow (julia-repl + Revise) to julia-snail, and I think I mostly get how things should work but I'm not quite sure.

Basically I'm seeing a difference in the main way that code is evaluated between the two packages:
- In julia-repl, your REPL is just a normal Julia REPL, which means that it treats the package you're working on as basically any other package. Code you evaluate in this REPL is treated as "outside" code, but the code that your REPL has access to stays updated nicely if you use Revise.
- In julia-snail, your REPL runs "inside" the package you're developing. When you send a block of code to it, you're basically doing `@eval MyModule ...code...`. This means you can access module-internal variables/functions/etc. really easily which is cool. Code stays updated by you explicitly telling julia-snail to evaluate a new version of a function.

So my main question here is basically to do with Revise in the context of julia-snail.
If I have some function in my code that I later modify, then I can send the function definition to julia-snail, which overwrites the old definition with the new one.
**If I skip the step of sending the code to julia-snail, is there any way that Revise can be made aware of the updated function and call it instead of the old version?**
If I can't, I'm sure I'll get used to using `C-c C-c` whenever I make changes, but it would be super cool if I didn't have to.

Hopefully this makes sense, let me know if you need more clarification.

**Comment by dahtah** [comment]
My impression is that this bound to be a confusing issue for a lot of users, because Revise largely obviates the need for ever loading stuff into the REPL. The workflow I use is Revise for packages, so that for anything in the src/ directory there is no need to use julia-snail's own code-loading facilities. I use them only for scripts and examples. 
Another possible workflow is to not use Revise at all for packages, and use julia-snail exclusively. I'm not sure there's a benefit to be had from mixing up the two? Perhaps there's should be some workflow recommendation in the doc.

**Comment by orialb** [comment]
In the julia-snail REPL you can do: 
1. `using Revise; using MyPackage`
2. Run `julia-snail-update-module-cache` from the file defining `MyPackage`  so Snail will be aware of all the files included in the package. 

This way you will have Revise tracking the code, and you will also get nice code completion and xref features via Snail when working inside the package code. 
This will work as long as you don't use `julia-snail-send-top-level-form` or `julia-snail-send-region`. Those command seem to break Revise code tracking.
(see also discussion in https://github.com/gcv/julia-snail/issues/18).

There are other advantages of loading the package code with `using` instead of `julia-snail-send-buffer-file`: It brings `export`ed functions to the main scope and also it allows you to work in a clean environment and see how the package would like to a user who installed it.

**Comment by gcv** [comment]
I improved Revise support and added some workflow documentation to the wiki: https://github.com/gcv/julia-snail/wiki/Tips-and-Tricks#workflow
