### ISSUE TITLE
Use tree-sitter for parsing

### ISSUE THREAD

**Issue by kskyten** [gcv/julia-snail#29]
There is an [emacs package](https://github.com/ubolonton/emacs-tree-sitter) for interfacing with the [tree-sitter](https://github.com/tree-sitter/tree-sitter) parser. It supports Julia.

**Comment by gcv** [comment]
I know about Tree-sitter, it's really cool. Unfortunately, it's also yet another heavy dependency, since it requires a native module. It's bad enough that Snail requires vterm, and I want to eliminate that dependency in the future. To justify adding Tree-sitter, it has to offer substantially more than the current parser.

**Comment by kskyten** [comment]
Yes, the heavy dependency is unfortunate. I would like to be able to generate docstrings from function signatures and getters from a struct definition. Can that be achieved with the current parser? Better documentation lookup would be really great, but this is probably easier to handle from the Julia side. How does the communication work currently? Would it make sense to use https://github.com/kiwanami/emacs-epc?

**Comment by gcv** [comment]
> I would like to be able to generate docstrings from function signatures and getters from a struct definition. Can that be achieved with the current parser?

Not easily. The parser generator library I used, [Parsec](https://github.com/cute-jumper/parsec.el), is easy to use but slow. I had to massively simplify Julia's syntax to achieve adequate performance. This included swallowing parentheses whole, so extracting function parameter lists requires workarounds.

> Better documentation lookup would be really great

What do you have in mind?

**Comment by kskyten** [comment]
For the documentation lookup I was thinking of something along the lines of https://github.com/tkf/InteractiveCodeSearch.jl. Would be nice to be able to parse/infer types of arguments to narrow the search as well.

**Comment by gcv** [comment]
It's not as nifty as `InteractiveCodeSearch.jl`, but the Emacs built-in `xref-find-apropos` does something similar, and Snail interoperates with it. Use `helm-xref` or `ivy-xref` or something similar for a nicer interface. You should update Snail before trying; I just made some small changes. (I also found a bug with looking up sources for built-in packages, #30, but the feature should be useful regardless.)

A parser cannot infer argument type except for trivial literals, so that won't happen even if the Snail parser gets a major upgrade.

**Comment by kskyten** [comment]
I think literal types would be sufficient, you can narrow it down further interactively.

**Comment by gcv** [comment]
We've substantially revised the Julia parsing story. See #33 and 34498596550b0f81. If there are specific further enhancements you'd like to see, please open separate tickets.
