### ISSUE TITLE
Support module detection for included files

### ISSUE THREAD

**Issue by gcv** [gcv/julia-snail#9]
Consider the following case:

File `MyModule.jl`:
```julia
module MyModule

include("a1.jl")

end
```

File `a1.jl`:
```julia
function f1()
    "hello world"
end
```

The contents of file `a1.jl` are part of `MyModule`, and should be detected as such by Snail.

The parser should detect `include` calls inside (potentially nested) modules, and when called upon to detect what module `a1.jl` is in return `MyModule` instead of `Main`. This should be doable with an in-memory data structure, mapping from filename to module.

**Comment by gcv** [comment]
@orialb: I finished a first attempt at implementing this feature, which we discussed [on Discourse](https://discourse.julialang.org/t/ann-julia-snail-an-emacs-development-environment-first-beta-release/35786/28). I still have to write some tests for it, but it seems to work for me so far.

The feature branch is not merged yet: https://github.com/gcv/julia-snail/tree/include-detection
Documentation link: https://github.com/gcv/julia-snail/tree/include-detection#module-nested-includes

If you have time to try this branch, I'll appreciate any comments or bug reports.

**Comment by orialb** [comment]
Awesome! I will have a look this week.

**Comment by orialb** [comment]
Just wanted to let you know that I started using the feature branch on my machine. From a quick check it seems that completion and xref commands are working across module files, very nice!

Unfortunately at the moment I am mainly writing Latex instead of Julia code, so I didn't have the chance to really test this in regular usage. Hopefully soon I will have some excuse to do some coding work for one of my projects so I could test this more thoroughly.

**Comment by gcv** [comment]
Cool. I just found and fixed several bugs in that feature, and added some tests. Branch is now merged in and ready for people to find bugs in it.
