### ISSUE TITLE
[Suggestion] use lsp-bridge to make completion

### ISSUE THREAD

**Issue by nesteiner** [gcv/julia-snail#98]
in emacs china, there is a dude developing a very fast lsp client https://github.com/manateelazycat/lsp-bridge  
it is pretty cool, I think you should take a try.  
I notice that there is a feature for completion, why not try `lsp-bridge` to complete julia code ?  :yum:

**Comment by gcv** [comment]
The idea of integrating Snail with LSP has come up before, and I don't understand it. LSP requires running an additional server and additional setup on the Emacs side. For lsp-bridge, it seems to also require Python. What value does LSP add relative to Snail itself? I saw a discussion about lsp-bridge on Reddit earlier, and while it looks cool, its main selling point seems to be performance. I don't find Snail's completion slow, especially since it delegates nearly all the work to the completion mechanism built into Julia's native REPL.

**Comment by nesteiner** [comment]
python is for develop core of `lsp-bridge`, if you want to add language support, please look at `langserver`, there are so many example.  I think you can add language support for julia
